# Generated by Django 3.2.12 on 2022-04-10 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('appointment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('appointment_time', models.DateTimeField()),
                ('appointment_status', models.CharField(max_length=10)),
                ('appointment_description', models.CharField(max_length=100)),
                ('appointment_type', models.CharField(max_length=100)),
                ('appointment_category', models.CharField(max_length=100)),
                ('staff_phone_number', models.IntegerField(max_length=15)),
                ('student_phone_number', models.IntegerField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('staff_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('staff_first_name', models.CharField(max_length=100)),
                ('staff_middle_name', models.CharField(max_length=100)),
                ('staff_surname', models.CharField(max_length=100)),
                ('staff_office', models.CharField(max_length=100)),
                ('staff_role', models.CharField(max_length=50)),
                ('staff_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='F', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('student_reg_number', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('student_first_name', models.CharField(max_length=100)),
                ('student_middle_name', models.CharField(max_length=100)),
                ('student_surname', models.CharField(max_length=100)),
                ('student_degree_program', models.CharField(max_length=100)),
                ('student_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='F', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_phone_number', models.IntegerField()),
                ('user_password', models.CharField(max_length=100)),
                ('staff_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD_backend.staff')),
                ('student_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD_backend.student')),
            ],
        ),
        migrations.CreateModel(
            name='task',
            fields=[
                ('task_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('task_issue_date', models.DateTimeField()),
                ('task_feedback_file', models.FileField(upload_to='')),
                ('task_type', models.CharField(max_length=100)),
                ('task_description', models.CharField(max_length=100)),
                ('appointment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD_backend.appointment')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD_backend.staff')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD_backend.staff'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='student_reg_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD_backend.student'),
        ),
    ]
