# Generated by Django 3.2.9 on 2022-05-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_deadline_date',
            field=models.DateField(default='2022-06-12'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_category',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_issue_date',
            field=models.DateField(),
        ),
    ]
