# Generated by Django 3.0 on 2022-05-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_associated_group_name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
