# Generated by Django 3.2.12 on 2022-04-10 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='staff_phone_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='student_phone_number',
            field=models.IntegerField(),
        ),
    ]
