# Generated by Django 3.2.12 on 2022-04-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD_backend', '0002_auto_20220410_1543'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='users',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='appointment_description',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='appointment_status',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='appointment_time',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_feedback_file',
        ),
        migrations.AddField(
            model_name='student',
            name='student_fingerprint_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_category',
            field=models.CharField(choices=[('Priv', 'Private'), ('Acad', 'Academic'), ('Other', 'Others')], default='Acad', max_length=10),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('Indiv', 'Individual'), ('Grp', 'Group')], default='Indiv', max_length=10),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_middle_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_middle_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
