# Generated by Django 3.0 on 2022-04-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD_backend', '0002_appointment_appointment_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_status',
            field=models.CharField(default='pending', max_length=15),
            preserve_default=False,
        ),
    ]
