# Generated by Django 3.0 on 2022-04-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD_backend', '0002_auto_20220427_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_email',
            field=models.EmailField(max_length=255),
        ),
    ]
