# Generated by Django 3.0 on 2022-04-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD_backend', '0003_appointment_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='staff_role',
            field=models.CharField(default='Superviser', max_length=100),
            preserve_default=False,
        ),
    ]
