# Generated by Django 3.2.12 on 2022-04-15 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD_backend', '0003_auto_20220414_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='staff_username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CRUD_backend.staff'),
        ),
        migrations.AlterField(
            model_name='user',
            name='student_username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CRUD_backend.student'),
        ),
    ]
