# Generated by Django 3.0 on 2022-04-29 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD_backend', '0004_staff_staff_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateField(auto_now=True),
        ),
    ]
