# Generated by Django 3.0.5 on 2022-04-29 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD_backend', '0005_appointment_appointment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
