# Generated by Django 3.0.5 on 2022-04-29 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD_backend', '0006_appointment_appointment_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='appointment_time',
        ),
    ]
