# Generated by Django 3.0.5 on 2022-04-29 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD_backend', '0007_remove_appointment_appointment_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='appointment_date_time',
        ),
    ]
